## A sample configuration for trade reconcilers
---
rootNodeMappings: 
    com.fluxtion.learning.fx.example6.reconciler.nodes.TradeReconciler: classifier
config:
    reconilers:
        REUTERS_DC1:
            venues: [dc_ln_1, MiddleOffice]
            reconcileExpiry: 10
            publishFrequency: 2
        EBS_LD4:
            venues: [LD_4, MiddleOffice, triana]
            reconcileExpiry: 5
            publishFrequency: 2
        EBS_NY2:
            venues: [NY_2, MiddleOffice, triana]
            reconcileExpiry: 9
            publishFrequency: 2
        
