## A sample configuration for trade reconcilers
---
rootNodeMappings: 
    com.fluxtion.learning.fx.example6.reconciler.nodes.TradeReconciler: classifier
config:
    defaults:
        reconcileTimeout: 10
        publishFrequency: 6
        checkExpiredFrequency: 2
    reconcilers:
        REUTERS_DC1:
            venues: [dcln_1_reuters, MiddleOffice_reuters_dc1]
        EBS_LD4:
            venues: [LD_4_EBS, MiddleOffice_EBS_LD4, triana_EBS_LD4]
            reconcileTimeout: 5
            publishFrequency: 2
            checkExpiredFrequency: 1
        EBS_NY2:
            venues: [NY_2, MiddleOffice_NY2]
            publishFrequency: 3
        FXALL_NY3:
            venues: [NY_3_FXALL, MiddleOffice_NY3_FXALL]
            checkExpiredFrequency: 17
        
